wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.8
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1712770569.0
    t:
      1:
      - 1
      - 50
      - 55
      2:
      - 1
      - 50
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.9.8
      5: 0.16.6
      8:
      - 3
      - 5
      10:
      - 3
      13: windows-amd64
deploy:
  desc: null
  value: true
tag:
  desc: null
  value: scratch
seed:
  desc: null
  value: 0
out_dir:
  desc: null
  value: out_single_graph_p_925
eval_interval:
  desc: null
  value: 1
log_interval:
  desc: null
  value: 1
save_ckpt_interval:
  desc: null
  value: 1
eval_iters:
  desc: null
  value: 200
eval_only:
  desc: null
  value: false
always_save_checkpoint:
  desc: null
  value: true
init_from:
  desc: null
  value: scratch
wandb_project:
  desc: null
  value: chainofthoughtaug30
wandb_run_name:
  desc: null
  value: gpt2
dataset_path:
  desc: null
  value: single_graph_n200_p95_frac02/
vocab_size:
  desc: null
  value: 100
gradient_accumulation_steps:
  desc: null
  value: 1
batch_size:
  desc: null
  value: 64
block_size:
  desc: null
  value: 128
n_layer:
  desc: null
  value: 2
n_head:
  desc: null
  value: 1
n_embd:
  desc: null
  value: 64
num_experts:
  desc: null
  value: 8
expert_k:
  desc: null
  value: 1
dropout:
  desc: null
  value: 0.0
bias:
  desc: null
  value: false
learning_rate:
  desc: null
  value: 0.0006
max_iters:
  desc: null
  value: 40000
optimizer:
  desc: null
  value: AdamW
weight_decay:
  desc: null
  value: 0.1
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.95
grad_clip:
  desc: null
  value: 1.0
decay_lr:
  desc: null
  value: true
warmup_iters:
  desc: null
  value: 20
lr_decay_iters:
  desc: null
  value: 600000
min_lr:
  desc: null
  value: 0.0006
backend:
  desc: null
  value: nccl
device:
  desc: null
  value: cuda
compile:
  desc: null
  value: false
top_k:
  desc: null
  value: 10
temperature:
  desc: null
  value: 1
num_samples_generated_for_accuracy:
  desc: null
  value: 1
